### ISSUE TITLE
"adaptDA" package

### ISSUE THREAD

**Issue by zhjianli** [dncR/MLSeq#5]
Hi, I am using R 4.0.5. R asked me to install the "adaptDA" package when I used the classify function. However, I was not able to install the package since I always got the same error message "package ‘adaptDA’ is not available for this version of R".  Do I have to downgrade my R version? Or is there another way? Thanks.

**Comment by dncR** [comment]
Hello @zhjianli,

MLSeq is mainly dependent on "caret" package. However, this problem may arise from reverse dependency of any package that we are dependent on. "adaptDA" package seems to be removed from CRAN. You may download the source files of latest version from CRAN archive, and locally install adaptDA package. This might be a solution. I belive this package will be removed from reverse dependencies. 

Hope this helps.
